### ISSUE TITLE
Ultra2 okay, UltraMini no go for me

### ISSUE THREAD

**Issue by clarkc2** [Flameeyes/glucometerutils#31] opened 2017-12-04 18:47 UTC
Ultra2 w/ serial number KMQxxxxEY, GTIN: 00353885000277, 
UltraMini w/serial number (21) KPFxxxxER,  GTIN: 00353885002677

I wonder if my UltraMini needs a different driver?

On the same sync cable:

# python3 glucometer.py --driver otultra2 info
OneTouch Ultra 2 glucometer
Serial Number: KMQxxxxEY
Version Information:
    Software version: P02.00.00 30/08/06
Native Unit: mg/dL
Time: 2017-12-04 12:24:19

but...

# python3 glucometer.py --driver otultraeasy info
Traceback (most recent call last):
  File "glucometer.py", line 149, in <module>
    main()
  File "glucometer.py", line 88, in main
    device_info = device.get_meter_info()
  File "/usr/local/src/glucometerutils/glucometerutils/drivers/otultraeasy.py", line 249, in get_meter_info
    serial_number=self.get_serial_number(),
  File "/usr/local/src/glucometerutils/glucometerutils/drivers/otultraeasy.py", line 264, in get_serial_number
    response = self._read_response()
  File "/usr/local/src/glucometerutils/glucometerutils/drivers/otultraeasy.py", line 209, in _read_response
    response.read_from(self.serial_)
  File "/usr/local/src/glucometerutils/glucometerutils/drivers/otultraeasy.py", line 96, in read_from
    _IDX_ETX, _ETX, self.cmd[_IDX_ETX]))
glucometerutils.support.lifescan.MalformedCommand: Invalid response received:
Malformed command: at position -3 expected 03, received 06

**Comment by Flameeyes** [comment] 2017-12-04 23:28
This appears like a duplicate of issue #29, which I have not had a chance to debug yet, as my meters were still being delivered from my move. I'll look into it ASAP.

**Closed** 2017-12-04 23:28 UTC
